site_name: BLIKVM 用户手册
docs_dir: '../../docs/zh'
site_dir: '../../generated/zh'
site_description: Open and cheap DIY IP-KVM on Raspberry Pi
site_author: Thomas Von
theme:
  name: material
  custom_dir: '../../overrides/'
  logo: assets/images/logo.png
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  features:
    - content.code.annotate
    - navigation.indexes
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - navigation.expand
    - search.highlight
    - search.share
    - search.suggest

extra:
  homepage: https://www.blicube.com
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ThomasVon2021/blikvm-site
      name: 加入到翻译工作中
  alternate:
    - name: English
      link: /blikvm/en/
      lang: en
    - name: 中文
      link: /blikvm/zh/
      lang: zh
repo_name: blikvm
repo_url: https://github.com/ThomasVon2021/blikvm.git
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
    - "快速开始":
        - "BLIKVM介绍": index.md
        - "HAT版本":
          - "BLIKVM HAT导览": BLIKVM-HAT-guide.md
          - "安装说明": BLIHAT-Installation.md
        - "BLIKVM CM4导览": BLIKVM-CM4-guide.md
        - "PCIe版本":
          - "BLIKVM PCIe导览": BLIKVM-PCIE-guide-zh.md
          - "安装说明": BLIKVM-PCIe-installation-zh.md
    - "配置":
        - "烧录镜像": flashing_os.md
        - "OLED显示器": OLED-display.md
    - "配件手册":
        - "ATX用户手册": atx-guide.md
        - "HDMI转CSI & Audio模块用户手册": hdmi-csi-i2s.md
        - "USB一分二用户手册": usb-splitter-guide.md